# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0739bd12f1a9727c4fcbc381f77342e241df2f3a1ad4a7157789a3b70344b65d59141ab9c6b50f9b7ce6fe6b04902499375fb72312e5ba563ec2507a97165f69

test:
  secret_key_base: 60cae72002e6c83f0a93bf328f32a7d53f5498a705bbebdf9fec0302cb637d484254cbfc8754147da6270907c98618ef05d9ea96911466115047b54197d7ad0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
